
- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='{{ mysql_root_name }}' AND Host NOT IN ('localhost', '127.0.0.1', '::1')

- name: Get list of hosts for the root user.
  command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = '{{ mysql_root_name }}' ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  check_mode: no

- name: Get list of hosts for the anonymous user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  check_mode: no

- name: Remove anonymous MySQL users.
  mysql_user:
    name: ''
    host: '{{ item }}'
    state: absent
  with_items: '{{ mysql_anonymous_hosts.stdout_lines|default([]) }}'

- name: Remove MySQL test database.
  mysql_db:
      name: test
      state: absent

- name: Get MySQL version.
  command: mysql --version
  register: mysql_cli_version
  changed_when: false

# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account (5.7.x).
  command: >
    mysql -u root -NBe
    'ALTER USER "{{ mysql_root_name }}"@"{{ item }}" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: '"5.7." in mysql_cli_version.stdout'

# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  command: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mysql_root_name }}"@"{{ item }}" = PASSWORD("{{ mysql_root_password }}");'
  with_items: "{{ mysql_root_hosts.stdout_lines|default([]) }}"
  when: '"5.7." not in mysql_cli_version.stdout'

