---

galaxy_info:
  author: "Martin Machac"
  company: "CSIRT-MU"
  min_ansible_version: 2.3.2
  platforms:
   - name: Debian
     versions:
      - all
   - name: Ubuntu
     versions:
      - all
dependencies: []

