
- name: configure elasticsearch
  lineinfile:
    path: '{{ file.name }}'
    regexp: '^({{ file.comments|default("#") }}[ \t]*)?{{ item.key }}{{ file.separator }}.*$'
    line: '{{ prefix }}{{ item.key }}{{ file.separator }}{{ item.value|default("") }}'
  with_items: '{{ file.config }}'
  notify: elk_elasticsearch_restart
  vars:
    prefix: '{% if item.state is defined and item.state == "absent" %}{{ file.comments|default("#") }}{% else %}{% endif %}'

