
- name: check remote existence of files
  stat:
      path: '{{ item }}'
  with_items: '{{ files.files }}'
  register: elk_logstash_configuration_files_remote_existence

- name: ensure existence of directory for files
  file:
      path: '{{ files.dir }}'
      state: directory

- name: copy files
  copy:
      remote_src: '{{ item.stat.exists }}'
      src: '{{ item.item }}'
      dest: '{{ files.dir }}/{{ item.item|basename }}'
  with_items: '{{ elk_logstash_configuration_files_remote_existence.results }}'

