
- name: install logstash
  apt:
    name: logstash=1:6.5.4-1
  notify: elk_logstash_start

- include_tasks: files.yml
  with_items:
    - dir: '{{ elk_logstash_configuration_files_directory }}'
      files: '{{ elk_logstash_configuration_files }}' 
    - dir: '{{ elk_logstash_pattern_files_directory }}'
      files: '{{ elk_logstash_pattern_files }}'
  loop_control:
    loop_var: files

- name: enable logstash to run on boot
  service:
      name: logstash
      enabled: yes

- name: install plugins
  shell: '{{ elk_logstash_plugin_command }} list | grep -w {{ item }} && echo Already installed || {{ elk_logstash_plugin_command }} install {{ item }}'
  register: elk_logstash_plugin_installation
  changed_when: 'elk_logstash_plugin_installation.stdout_lines[-1] != "Already installed"'
  with_items: '{{ elk_logstash_plugins }}'

