# heslo je manager-gcomp
- name: Create management user
  user:
    name: manager
    comment: System management
    groups: sudo
    shell: /bin/bash
    generate_ssh_key: yes
    password: '$6$UuC1Kh5VFZ5i2qle$dwGReQk/lj4aZXEUfKuLsLm5mp2bU3Gm10NtgLfuq.NkXza8DR98d3K7OseQvobGWENfKXB5dsayidMG/jYCm.'

- name: Remove kali user
  user:
    name: kali
    state: absent
    remove: true
    
- name: Install sshpass
  apt:
    name: sshpass
    state: present
    
- name: Create directories for task validation
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: manager
    mode: 0775
  loop:
    - /home/manager/check_tasks/
    - /home/manager/check_tasks/files/
    
- name: Copy task check scripts
  copy:
    src: "{{ item }}"
    dest: /home/manager/check_tasks/
    owner: root
    mode: u=rw,g=r,o=x
  loop:
    - "task1_test"
    - "task2_test"
    - "task3_test"
    - "task4_test"
    - "task5_test"

#---------------- Fix DNS server missing after reboot ---------------    

- name: Add DNS server to interfaces
  lineinfile:
    path: /etc/network/interfaces
    state: present
    regexp: '^    dns-nameservers'
    insertbefore: '^# END eth0'
    line: "    dns-nameservers 10.0.2.3"


    
- name: Reboot host
  command: reboot   
