---

galaxy_info:
  author: "Martin Machac"
  company: "CSIRT-MU"
  min_ansible_version: 2.6.0
  platforms:
   - name: EL
     versions:
      - 7     
   - name: Debian
     versions:
      - all
   - name: Ubuntu
     versions:
      - all
dependencies: []

