galaxy_info:
    role_name: mysql
    author: Kamil Andoniadis
    description: Secure installation of MySQL
    licence: MIT
    min_ansible_version: 2.3.3
    platforms:
        - name: Debian
          versions:
              - all
