---
# File: java-8/tasks/installation/redhat/main.yml
# Description:
# This task installs Oracle JDK into a system
# with RedHat based OS.

- name: RedHat -> download Java RPM
  get_url:
    headers: 'Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
    dest: "{{ java_dir_source }}/{{ java_rpm_filename }}"
    url: "{{ java_rpm_url }}"
    validate_certs: "{{ java_rpm_validate_certs }}"
    timeout: "{{ java_download_timeout }}"
    force: no
  register: java_task_rpm_download
  until: java_task_rpm_download|succeeded 
  become: yes

- name: RedHat -> install RPM
  yum:
    name: "{{ java_dir_source }}/{{ java_rpm_filename }}"
    state: present
  when: not java_task_rpm_download|skipped
  become: yes

- name: RedHat -> set Java version as default
  alternatives:
    name: "{{ item.executable }}"
    link: "/usr/bin/{{ item.executable }}"
    path: "{{ item.path }}/{{ item.executable }}"
  with_items:
    - { path: "{{ java_home }}/bin", executable: 'java' }
    - { path: "{{ java_home }}/bin", executable: 'keytool' }
    - { path: "{{ java_home }}/bin", executable: 'javac' }
    - { path: "{{ java_home }}/bin", executable: 'javadoc' }
  become: yes
  when: (
          java_set_as_default and
          java_task_rpm_download is defined and
          java_task_rpm_download|changed
        ) or (
          java_set_as_default and
          java_installed is defined and
          java_installed and
          java_version_installed is defined and
          java_version_installed != java_version_string)
  register: java_task_set_default
