---
# File: java-8/tasks/installation/debian/main.yml
# Description:
# This task installs Oracle JDK into a system
# with Debian based OS.

- name: Debian -> ensure essential packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - dirmngr

- name: Debian -> ensure the APT repository key is present
  apt_key:
    id: "{{ java_apt_repository_key }}"
    keyserver: keyserver.ubuntu.com
    state: present
  when: java_apt_repository_key is defined
  become: yes

- name: Debian -> ensure the APT repository is present
  apt_repository:
    repo: "{{ java_apt_repository }}"
    update_cache: yes
    state: present
  become: yes

- name: Debian -> set license as accepted
  debconf:
    name: "{{ java_deb_package }}"
    question: "{{ java_license_version }}"
    value: 'true'
    vtype: 'select'
  become: yes

- name: Debian -> ensure Java is installed
  apt:
    name: "{{ java_deb_package }}"
    state: "{{ java_state }}"
    cache_valid_time: "{{ java_cache_valid_time }}"
    update_cache: yes
    allow_unauthenticated: yes
  register: java_task_apt_install
  become: yes

- name: Debian -> set Java version as default
  apt:
    name: "{{ java_debconf_package_default }}"
    state: latest
  register: java_task_set_default
  when: java_set_as_default
  become: yes
