
- name: install suricata
  apt: 
    name: 'suricata'
    state: present
    update_cache: yes
  become: yes
  
- name: config address
  lineinfile:
    path: /etc/suricata/suricata.yaml
    regexp: '^    HOME_NET: '
    line: '    HOME_NET: "[10.10.30.0/24]"'
    
- name: config interface
  lineinfile:
    path: /etc/suricata/suricata.yaml
    regexp: '^  - interface: eth0'
    line: '  - interface: eth1'
    firstmatch: yes
    
- name: config use-nmap
  lineinfile:
    path: /etc/suricata/suricata.yaml
    regexp: '^    use-nmap: no'
    insertafter: '^    #use-mmap: no'
    line: '    use-nmap: yes'
    firstmatch: yes
    
- name: suricata-update
  command: suricata-update
  notify: restart_suricata
  become: yes


