---
- name: Ensure phpmyadmin directory exists
  file:
    path: /usr/share/phpmyadmin
    state: directory
    
- name: Download and extract phpmyadmin source
  unarchive:
    src: "{{ php_source_repo }}"
    dest: /usr/share/phpmyadmin
    remote_src: yes
    mode: 0755
    extra_opts: --strip-components=1
    
- name: Create config file from sample config
  copy:
    src: /usr/share/phpmyadmin/config.sample.inc.php
    dest: /usr/share/phpmyadmin/config.inc.php

- name: Ensure phpMyAdmin is configured in Apache.
  blockinfile:
    path: /etc/apache2/apache2.conf
    block: |
      Alias /phpmyadmin /usr/share/phpmyadmin

      <Directory /usr/share/phpmyadmin>
          Options Indexes FollowSymLinks
          DirectoryIndex index.php
      </Directory>

      # Disallow web access to directories that don't need it
      <Directory /usr/share/phpmyadmin/libraries>
          Order Deny,Allow
          Deny from All
      </Directory>
      <Directory /usr/share/phpmyadmin/setup/lib>
          Order Deny,Allow
          Deny from All
      </Directory>
    mode: 0644
  notify: apache_restart 